/**
 * 
 * 
 * Description : This class used for setting the TopicEntity.
 * 
 * @author Bhagawantha
 * @version 1.0
 * @see
 * @since Dec 08, 2016
 */
package com.chatbox.cms.entity;

// Generated Dec 7, 2016 5:53:44 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TopicEntity generated by hbm2java
 */
@Entity(name="TopicEntity")
@Table(name = "topic")
public class TopicEntity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1643881668323425747L;
	
	private Integer topicId;
	private String topicName;
	private String description;
	private String createdBy;
	private Date createdOn;
	private String updatedBy;
	private Date updatedOn;
	private Set<TopicAttachmentEntity> topicAttachmentEntities = new HashSet<TopicAttachmentEntity>(
			0);
	private Set<TopicCommentEntity> topicCommentEntities = new HashSet<TopicCommentEntity>(0);

	public TopicEntity() {
	}

	public TopicEntity(String topicName, String description, String createdBy,
			Date createdOn, String updatedBy, Date updatedOn,
			Set<TopicAttachmentEntity> topicAttachmentEntities,
			Set<TopicCommentEntity> topicCommentEntities) {
		this.topicName = topicName;
		this.description = description;
		this.createdBy = createdBy;
		this.createdOn = createdOn;
		this.updatedBy = updatedBy;
		this.updatedOn = updatedOn;
		this.topicAttachmentEntities = topicAttachmentEntities;
		this.topicCommentEntities = topicCommentEntities;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "topic_id", unique = true, nullable = false)
	public Integer getTopicId() {
		return this.topicId;
	}

	public void setTopicId(Integer topicId) {
		this.topicId = topicId;
	}

	@Column(name = "topic_name", length = 150)
	public String getTopicName() {
		return this.topicName;
	}

	public void setTopicName(String topicName) {
		this.topicName = topicName;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "created_by", length = 150)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_on", length = 19)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "updated_by", length = 150)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_on", length = 19)
	public Date getUpdatedOn() {
		return this.updatedOn;
	}

	public void setUpdatedOn(Date updatedOn) {
		this.updatedOn = updatedOn;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "topicEntity")
	public Set<TopicAttachmentEntity> getTopicAttachmentEntities() {
		return this.topicAttachmentEntities;
	}

	public void setTopicAttachmentEntities(Set<TopicAttachmentEntity> topicAttachmentEntities) {
		this.topicAttachmentEntities = topicAttachmentEntities;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "topicEntity")
	public Set<TopicCommentEntity> getTopicCommentEntities() {
		return this.topicCommentEntities;
	}

	public void setTopicCommentEntities(Set<TopicCommentEntity> topicCommentEntities) {
		this.topicCommentEntities = topicCommentEntities;
	}

}
