/**
 * 
 * 
 * Description : This class used for setting TopicAttachmentEntity.
 * 
 * @author Bhagawantha
 * @version 1.0
 * @see
 * @since Dec 08, 2016
 */
package com.chatbox.cms.entity;

// Generated Dec 7, 2016 5:53:44 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TopicAttachmentEntity generated by hbm2java
 */
@Entity
@Table(name = "topic_attachment")
public class TopicAttachmentEntity implements java.io.Serializable {

	
	
	/**
	 * 
	 */
	private static final long serialVersionUID = -4550253166883074474L;
	private Integer attachmentId;
	private TopicEntity topicEntity;
	private String fileLocation;
	private String createdBy;
	private Date createdOn;
	private String updatedBy;
	private Date updatedOn;

	public TopicAttachmentEntity() {
	}

	public TopicAttachmentEntity(TopicEntity topicEntity, String fileLocation, String createdBy,
			Date createdOn, String updatedBy, Date updatedOn) {
		this.topicEntity = topicEntity;
		this.fileLocation = fileLocation;
		this.createdBy = createdBy;
		this.createdOn = createdOn;
		this.updatedBy = updatedBy;
		this.updatedOn = updatedOn;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "attachment_id", unique = true, nullable = false)
	public Integer getAttachmentId() {
		return this.attachmentId;
	}

	public void setAttachmentId(Integer attachmentId) {
		this.attachmentId = attachmentId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "topic_id_fk")
	public TopicEntity getTopicEntity() {
		return this.topicEntity;
	}

	public void setTopicEntity(TopicEntity topicEntity) {
		this.topicEntity = topicEntity;
	}

	@Column(name = "file_location")
	public String getFileLocation() {
		return this.fileLocation;
	}

	public void setFileLocation(String fileLocation) {
		this.fileLocation = fileLocation;
	}


	@Column(name = "created_by", length = 150)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_on", length = 19)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "updated_by", length = 150)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_on", length = 19)
	public Date getUpdatedOn() {
		return this.updatedOn;
	}

	public void setUpdatedOn(Date updatedOn) {
		this.updatedOn = updatedOn;
	}

}
